### ISSUE TITLE
Slow response for iframe.html

### ISSUE THREAD

**Issue by sega-yarkin** [rabbitmq/sockjs-erlang#7]
I've tested performance of response to /stomp/iframe.html, for 5 cores (Xeon 2.30GHz) it was only ~1000 requests per second, which is too slow for static resource.

(P.S. I found in code that it every time does replace SockjsUrl in template and calculate MD5 hash. Maybe is better to do it at application start to save resources and time?)

**Comment by essen** [comment]
Yes, it does look quite inefficient. It wouldn't be too difficult to do something to fix it I believe. I'll check tomorrow.

**Comment by essen** [comment]
Looking into this now. I'm not convinced changing the code will lead to a significant speed up. We can of course perform both things beforehand, but then we have to memory copy the iframe file for every request due to how Erlang processes work.

I'm wondering why you have only about 1000 requests/s though. I have 10K reqs/s for this URL without tweaking anything or closing any other program on my laptop, which makes me think there might be a different problem on your end. Perhaps your fd limit is too low or something?

**Comment by sega-yarkin** [comment]
Hi, thanks for your reply, I dunno why we have different results, but I can reproduce it on many our nodes.
I use RabbitMQ 3.5.6, Erlang 18.1. In `rabbitmq.config` I've:

``` erlang
{rabbitmq_web_stomp, [
    { port, 15674 },
    { nb_acceptors, 500 },
    { sockjs_opts, [{ sockjs_url, "//cdn.../..../sockjs-min.js" }] }
]}
```

And run `ab -k -n 40000 -c 10 "http://127.0.0.1:15674/stomp/iframe.html"`.
When test was running management plugin said that I use 392 of 102400 fds, and 335 of 92068 sockets only.
Test gave this result:

```
Concurrency Level:      10
Time taken for tests:   36.365 seconds
Complete requests:      40000
Failed requests:        0
Write errors:           0
Keep-Alive requests:    40000
Total transferred:      30160000 bytes
HTML transferred:       19280000 bytes
Requests per second:    1099.95 [#/sec] (mean)
Time per request:       9.091 [ms] (mean)
Time per request:       0.909 [ms] (mean, across all concurrent requests)
Transfer rate:          809.92 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:     1    9   4.1      9      33
Waiting:        1    9   4.1      9      33
Total:          1    9   4.1      9      33

Percentage of the requests served within a certain time (ms)
  50%      9
  66%     10
  75%     12
  80%     12
  90%     15
  95%     17
  98%     19
  99%     21
 100%     33 (longest request)
```

The server had very small load at test time. After this test I tried to do the same test, but call `/stomp/info` instead, and it gave me 12k rps (it's good).

**Comment by essen** [comment]
If I recall right, older Cowboy used to have an issue with ab that pretty much killed benchmarks with this tool (while working fine with siege and others). I don't remember the exact issue (probably keep-alive related) but it was fixed quite some time ago.

The Cowboy version on stable is old enough to still have this issue. The current version however works fine, is now used on master and I'm not seeing any problems:

```
$ ab -k -n 40000 -c 10 "http://127.0.0.1:15674/stomp/iframe.html"
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 4000 requests
Completed 8000 requests
Completed 12000 requests
Completed 16000 requests
Completed 20000 requests
Completed 24000 requests
Completed 28000 requests
Completed 32000 requests
Completed 36000 requests
Completed 40000 requests
Finished 40000 requests


Server Software:        
Server Hostname:        127.0.0.1
Server Port:            15674

Document Path:          /stomp/iframe.html
Document Length:        484 bytes

Concurrency Level:      10
Time taken for tests:   3.292 seconds
Complete requests:      40000
Failed requests:        0
Keep-Alive requests:    39605
Total transferred:      30230520 bytes
HTML transferred:       19360000 bytes
Requests per second:    12151.44 [#/sec] (mean)
Time per request:       0.823 [ms] (mean)
Time per request:       0.082 [ms] (mean, across all concurrent requests)
Transfer rate:          8968.37 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:     0    1   0.5      1      15
Waiting:        0    1   0.5      1      15
Total:          0    1   0.5      1      15

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      1
  80%      1
  90%      2
  95%      2
  98%      2
  99%      3
 100%     15 (longest request)
```

If you can, try on master to confirm the issue is gone for you.

**Comment by sega-yarkin** [comment]
Hi again! We've updated our RabbitMQ installations to 3.6.0 release and this issue still actual. On 5 Xeon cores RMQ gave to us only near 1.1-1.2k rps, I've tried apache bench and JMeter (same results). Why do you have 12k but we only 1.2k? :-)

**Comment by essen** [comment]
Especially on a mere i7 thin laptop...

Probably has to do with configuration. What does ulimit -a say?

**Comment by sega-yarkin** [comment]
Limits under current `beam.smp` process are:

```
# cat /proc/45836/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             4096                 31195                processes
Max open files            102400               102400               files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       31195                31195                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

or you interested of limits under root account?

**Comment by sega-yarkin** [comment]
When test is active on management console I have:
![rabbitmq](https://cloud.githubusercontent.com/assets/1433049/12034984/ec8c80f0-ae48-11e5-9385-afb72eb6c61a.PNG)

**Comment by essen** [comment]
What does the CPU usage look like when running the benchmark?

**Comment by sega-yarkin** [comment]
From `htop`:
![htop_total](https://cloud.githubusercontent.com/assets/1433049/12035603/5f9e81b4-ae4f-11e5-8fd9-3743d22cb4d2.png)
![htop_procs](https://cloud.githubusercontent.com/assets/1433049/12035585/44276568-ae4f-11e5-80ad-2da201396eb8.png)
From `atop`:
![atop](https://cloud.githubusercontent.com/assets/1433049/12035613/63a9d6a0-ae4f-11e5-8388-d6ca84fe991b.png)

`atop` says that we have huge context switching (but same test to `/stomp/info` has c/w about 15-17k only).
`beam.smp` process has next command line options (maybe it contains some useful info):
`/usr/lib64/erlang/erts-7.2/bin/beam.smp -W w -A 0 -P 1048576 -K true -S 5:5 -sbt ts -sct L0-5c0-5 -B i -- -root /usr/lib64/erlang -progname erl -- -home /var/lib/rabbitmq -- -pa /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.0/ebin -noshell -noinput -s rabbit boot -sname rabbit@dev-eventmq-web1 -boot start_sasl -config /etc/rabbitmq/rabbitmq -kernel inet_default_connect_options [{nodelay,true}] -sasl errlog_type error -sasl sasl_error_logger false -rabbit error_logger {file,"/var/log/rabbitmq/rabbit@dev-eventmq-web1.log"} -rabbit sasl_error_logger {file,"/var/log/rabbitmq/rabbit@dev-eventmq-web1-sasl.log"} -rabbit enabled_plugins_file "/etc/rabbitmq/enabled_plugins" -rabbit plugins_dir "/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.0/plugins" -rabbit plugins_expand_dir "/var/lib/rabbitmq/mnesia/rabbit@dev-eventmq-web1-plugins-expand" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false -mnesia dir "/var/lib/rabbitmq/mnesia/rabbit@dev-eventmq-web1" -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672`

**Comment by essen** [comment]
The `-A 0` option means you disable the async thread pool. Those threads are used for I/O. They could be the reason for your performance problem. On my machine, when I go to the plugin and just do `make run-broker`, I get 64 async threads.

It might be worth testing with a different value. I'm not sure where this value gets configured but I do know it's configured as `+A` instead of `-A` that beam.smp later receives. Try increasing it.

**Comment by sega-yarkin** [comment]
I thought it for file I/O only, I've changed this parameters to 64 but nothing changed in the benchmark, 1000 rps.

**Comment by essen** [comment]
Try commenting out the md5 stuff to rule it out maybe?

**Comment by sega-yarkin** [comment]
I've installed RMQ from rpm package, do you mean I should make dev environment and compile sockjs plugin from source code?

**Comment by essen** [comment]
Yes. Just clone the rabbitmq-web-stomp repository, then run `make` then `make run-broker` and try to see if you can reproduce the benchmark numbers. If it's the same, then try commenting out the md5 and run benchmarks again.

This would help me a lot since I cannot reproduce the problem.

**Comment by sega-yarkin** [comment]
I dunno what happens but yes I have same result after replacing md5 to constant string and even commenting out format function, it has improved benchmark maybe for 10%. I have 700 rps on iframe.html (I've tested on other server) and 10k on info requests.. :-(

**Comment by sega-yarkin** [comment]
It's very funny, but I've copied all code from `iframe` to `info_test` and it still fast (20x faster).

```
info_test(Req, Headers, #service{websocket = Websocket,
                                 cookie_needed = CookieNeeded}) ->
    I = [{websocket, Websocket},
         {cookie_needed, CookieNeeded},
         {origins, [<<"*:*">>]},
         {entropy, sockjs_util:rand32()}],
    D = sockjs_json:encode({I}),
    %%
    SockjsUrl = "//cdn..../sockjs/1.0.3-p1/sockjs-min.js",
    IFrame = io_lib:format(?IFRAME, [SockjsUrl]),
    MD5 = "\"" ++ binary_to_list(base64:encode(erlang:md5(IFrame))) ++ "\"",
    %%
    H = [{"Content-Type", "application/json; charset=UTF-8"}, {"ETag", MD5}],
    sockjs_http:reply(200, H ++ Headers, D ++ IFrame, Req).
```

```
# ab -k -n 40000 -c 10 "http://127.0.0.1:15674/stomp/info"
...
Requests per second:    14153.47 [#/sec] (mean)
...
```

**Comment by essen** [comment]
Nice! OK let me take a look at what's different.

**Comment by essen** [comment]
OK two things to try, both on the same line here: https://github.com/rabbitmq/sockjs-erlang/blob/master/src/sockjs_handler.erl#L151
- Remove `[0-9-.a-z_]*` (keep only `/iframe.html`) then benchmark
- At the end of the line, instead of `[cache_for]`, put `[h_no_cache, xhr_cors]`, then benchmark

Before running `make run-broker` again you may need to run `make`.

**Comment by sega-yarkin** [comment]
Oh, second one resolved my problem, it gave 17.5k (and 17k then I reverted first one), and it produces only 20k context switching (10x lower than before). What `cache_for` is doing?

**Comment by essen** [comment]
Mostly date calculations and building. Some of this involves C code, looking into why it would do a context switch...

**Comment by sega-yarkin** [comment]
It's looks like problem in `httpd_util:rfc1123_date`, when I returned `cache_for` and commented out generating of `Expires` header in it I got good performance.

**Comment by essen** [comment]
Yes, that's where the issue lies. Apparently it calls conversion functions from Erlang that involve querying the current local time. This would most likely explain the context switches.

The fix should not be too difficult, I have a fast RFC1123 function in Cowboy, I just need to adapt it to accept an argument. I will come back to you next week with a patch to try, as I'm about done for the year now.

Thanks very much for your patience and help in figuring out this issue!

**Comment by sega-yarkin** [comment]
Thank you for your help too!

**Comment by sega-yarkin** [comment]
Hi @essen , are there any updates about this issue?

**Comment by essen** [comment]
I'm not forgetting about this but time ran out for today. Will try to squeeze it next week.

**Comment by essen** [comment]
Hello, considering we dropped SockJS in RabbitMQ 3.7.0 I doubt we will ever fix this.
